projeto_censo_eleicoes:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: genericproject2023
      dataset: censo_eleicoes_br
      location: US
      threads: 5
      keyfile: /tmp/gcp_key.json